version: '3'

services:
  db_app:
    container_name: db_app
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: frikyland
    volumes:
      - frikyland_db:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  web_app:
    depends_on:
      - db_app
    container_name: frikyland_app
    build: ./docker_files/
    volumes:
      - .:/var/www/html/frikyland
    ports:
      - "80:80"
volumes:
  frikyland_db: